name: compile_pdf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Add and commit PDF file
#        run: |
#         git config --global user.email "actions@github.com"
#         git config --global user.name "GitHub Actions"
#         git add out/main.pdf
#         git commit -m "added auto-compiled pdf"
#
#      - name: Push changes
#        uses: ad-m/github-push-action@main
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check commit message
        id: check_commit_message
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $commit_message == *"skip-ci"* ]]; then
            echo "Commit message contains 'skip-ci'. Skipping workflow."
            exit 78
          fi

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install texlive-full

      - name: Compile LaTeX to PDF
        run: pdflatex --output-directory=out main.tex

      - name: Add and commit PDF file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add out/main.pdf
          git commit -m "skip ci"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}