name: compile_pdf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-extra
          sudo apt-get install texlive-lang-cyrillic

      - name: Compile LaTeX to PDF
        run: |
          pdflatex main.tex
          pdflatex main.tex
          mkdir -p out
          mv main.pdf out/main.pdf

      - name: Pull latest changes from the remote repository
        run: git pull origin main

      - name: Add and commit PDF file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add out/main.pdf
          git commit -m "add auto-compile pdf"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}