name: compile_pdf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Install LaTeX
        run: sudo apt-get install texlive
      - name: ls
        run: ls
      - name: pwd
        run: echo "$PWD"
      - name: Compile LaTeX to PDF
        run: pdflatex -output-directory=out main.tex