name: example test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: creating input
        run: cd example && echo "1 2" >> in
      - name: running code
        run: cd example && ./a_plus_b < in > out
      - name: running stupid solution
        run: cd example && echo "3" >> out2
      - name: comparing output
        run: cd example && diff -s out out2
